### ISSUE TITLE
Добавить поддержку компилятора DMC

### ISSUE THREAD

**Issue by j123123** [bmstu-iu9/refal-5-lambda#176]
Есть такой компилятор C/C++ - доступен под достаточно либеральной лицензией https://github.com/DigitalMars/dmc/blob/master/LICENSE
Может быть можно добавить его поддержку в bootstrap.bat скрипт? Я попробовал просто прописать пути, как сказано в https://github.com/bmstu-iu9/refal-5-lambda#Установка-наwindows  - у меня не заработало с ходу (правда я проверял в Wine)

**Comment by j123123** [comment]
Кстати, зачем надо поддерживать совместимость с такими неактуальными компиляторами, как "Borland C++ Compiler 5.5" и "OpenWatcom"? Может еще "Turbo C++" попробовать?

**Comment by j123123** [comment]
А, уже есть. Я не заметил https://github.com/bmstu-iu9/refal-5-lambda/issues/73

**Comment by Mazdaywik** [comment]
> Кстати, зачем надо поддерживать совместимость с такими неактуальными компиляторами, как "Borland C++ Compiler 5.5" и "OpenWatcom"? Может еще "Turbo C++" попробовать?

Компилятор Borland — очень быстрый, это основной мой рабочий компилятор. Заметно медленнее — Visual C++, раза в полтора-два. Тормнозные — GCC C++, Clang и Open Watcom.

Open Watcom криво поддерживает стандарт и некоторые его ошибки напоминают стилевые подсказки. Например, если я забыл поставить избыточное пространство имён (там где стандарт его разрешает не ставить). Да и просто интересно поддержать и его тоже.

> Я попробовал просто прописать пути, как сказано в … - у меня не заработало с ходу (правда я проверял в Wine)

Подробности и содержимое `stdout`. Лучше создать об этом новую задачу.

**Comment by j123123** [comment]
> Компилятор Borland — очень быстрый, это основной мой рабочий компилятор. Заметно медленнее — Visual C++, раза в полтора-два. Тормозные — GCC C++, Clang и Open Watcom.

Тормознее по скорости компиляции, или по скорости того, что скомпилировано? На счет первого я еще поверить могу, но второе - сомнительно.

> Подробности и содержимое stdout. Лучше создать об этом новую задачу.

Зачем новую задачу? Можно в #73

**Comment by Mazdaywik** [comment]
Тормознее по скорости компиляции, она лимитирует. Условно: с BCC код на Рефале отрабатывает за 10 секунд, компиляция BCC — за 5 секунд. С G++ код на Рефале — 5 секунд, код G++ — 30 секунд. А по скорости — сравнимо с `g++ -O1` точно, про `-O2` — не уверен. `g++ -O0` медленее, чем BCC без флагов оптимизации (я их так и не понял, как их задавать).

**Comment by j123123** [comment]
Есть компилятор Zapcc, в котором как раз сделан упор на скорость компиляции, и он совершенно бесплатен. Можно его тоже попробовать.

**Comment by Mazdaywik** [comment]
> Есть компилятор Zapcc, в котором как раз сделан упор на скорость компиляции, и он совершенно бесплатен. Можно его тоже попробовать.

#177.
