### ISSUE TITLE
Файл Checker.sref

### ISSUE THREAD

**Issue by AnastasiaSkripacheva** [bmstu-iu9/refal-5-lambda#184]
Функция
```
PrepareMessage {
  #AlreadyDefined e.Name = 'Function ' e.Name ' already defined';
```
‘is already defined’
* [x] Грамматика. Иногда это также может опускаться, но раз в следующих строках программы у Вас указано ...‘is not defined’, то лучше поставить is и здесь 

```
  #InvalidMode s.OldMode s.NewMode e.Index
    = 'Variables ' s.OldMode '.' e.Index ' and 's.NewMode '.' e.Index ' has different modes';
```
* [x] have different modes, так как их перечислено несколько

```
  #MustBeHardPattern = 'Pattern of function specialization maust be hard';
```
* [x] Опечатка, must 

```
 #RepVarInSpecPattern s.Mode e.Index
    = 'Repeating Variable ' s.Mode '.' e.Index ' in specialization pattern';
```
* [x] По нормам английского языка здесь лучше использовать ‘repeated’, а не ‘repeating’, как раз дальше в тексте программы у Вас идёт:
```
CheckRepeatedVariables {
  e.Pattern = <ErrorsForRepeatedVariables <FindVariables e.Pattern>>;
}
```
И форма прилагательного выбрана уже правильно :)

**Comment by Mazdaywik** [comment]
Не надо, я их уже поправил. Просто если будет возможность писать с форматированием (будете с компьютера), то лучше выделяйте.

**Comment by Mazdaywik** [comment]
Исправил. @AnastasiaSkripacheva, проверьте, правильно ли исправил.
