### ISSUE TITLE
Исправление ошибок: 3-basics.en.md 

### ISSUE THREAD

**Issue by kategimranova** [bmstu-iu9/refal-5-lambda#220]
* [x] **_11_**: `there is no Refal-2 qualifiers` надо исправить на `there are no Refal-2 qualifiers`(qualifiers - множественное число)
* [x] **_21_**: `In the previous chapter we managed` => `In the previous chapter, we managed `(пропущена запятая)
* [x] **_35_**:  `which emphasize` =>  `which emphasizes` (глагол должен быть в единственном числе, так как речь идет о слове "empty")
* [x] **_82_**:` key word `=> `keyword`
* [x] **_85_**: `a rule, which define` =>` a rule, which defines` (rule - единственное число)
* [x] _**85**_: `arguments subset` => `argument subset` or `subset of arguments`
* [x] **_89_**: `Any sentence consist` => `Any sentence consists `(sentence - единственное число)
* [x] _**91**_: `a result that describe` => `a result that describes `(result - единственное число)
* [x] **_100_**: `with empty argument `=> `with an empty argument` (пропущен артикль)
* [x] **_111_**: `user` => `the user` (пропущен артикль)
* [x] **_119_**: `this two cases` => `these two cases` (cases - множественное число)
* [x] **_135_**: `Let us to conclude` => `let us conclude` (rule: let me/us + verb)
* [x] **_143_**: `The comment begin` => `The comment begins `(comment - единственное число)
* [x] **_151_**: `A sentence consist` => `A sentence consists` (sentence - единственное число)
* [x] **_393_**: `the preceding sentences has priority` => ` the preceding sentences have priority `(sentences -множественное число)
* [x] **_451_**: `a arbitrary` => `an arbitrary` (неправильный артикль)
* [x] **_750; 761; 981, 988_**: `Otherwise` => `Otherwise, `(rule: Use a comma to set off most conjunctive adverbs (however, otherwise, therefore etc.))
* [x] **_761_**: `if the argument don’t begin` => `if the argument doesn’t begin` (argument - единственное число)
* [ ] **_829_**: `While programing on Refal` => `While programming on Refal `(неправильное написание слова programming)

**Comment by Mazdaywik** [comment]
19 ошибок.
