### ISSUE TITLE
Исправление орфографических ошибок

### ISSUE THREAD

**Issue by kategimranova** [bmstu-iu9/refal-5-lambda#221]
**2-intro.en.md**

* [x] **_73_**: `allow the programmer` => `allows the programmer` (единственное число, так как речь идет об интерфейсе)

**README.en.md**

* [x] **_25_**: `allow to write` => `allow writing` (правило: _allow + объект + инфинитив_ или _allow + герундий_)
* [x] _**46**_: `that allows to monitor` => `that allows monitoring` (правило: _allow + объект + инфинитив_ или _allow + герундий_)
* [x] **_95_**: `well written` =>` well-written`
* [x] **_112_**: `I’ve build up` => `I’ve built up` (Present Perfect Tense)
* [x] **_306_**: `the language allows create` => `the language allows creating` (правило: _allow + объект + инфинитив_ или _allow + герундий_)
* [x] **_310, 338, 424_**: `key word` => `keyword`
* [x] **_380_**: `data bases `=>` databases`
* [x] **_381_**: `The language allow` => `The language allows` (language - единственное число)
* [x] **_460_**: `that GCC specify` => `that GCC specifies` (GCC - единственное число)
* [x] **_466_**: `created in witch will be specify` => `created in which will be specify` (тут явно не про ведьм) 

**3-basics.en-alt.md**

* [x] **_382_**: `it is not necessarily to create` =>` it is not necessary to create`

**Comment by Mazdaywik** [comment]
1+10+1 ошибок

**Comment by Mazdaywik** [comment]
6+6+6+6+6+19+12 = 61
