### ISSUE TITLE
Исправление ошибок [2]

### ISSUE THREAD

**Issue by kategimranova** [bmstu-iu9/refal-5-lambda#222]
### 3-basics.en.md

* [x] **_124_**: `tools development` => `tool development` (Правило: _прилагательные в английском языке не изменяются ни по родам, ни по числам, ни по падежам_)
* [x] **_159_**: `characters sequence` => `character sequence`  (Правило: _прилагательные в английском языке не изменяются ни по родам, ни по числам, ни по падежам_)
* [x] **_858_**: `this functions` => `these functions` (functions - множественное число)
* [x] **_912_**: `chain of letters and composed character` => `chain of letters and composed characters` (слово _character_ должно быть во множественном числе)

### 3-basics.en-alt.md
Правило: _прилагательные в английском языке не изменяются ни по родам, ни по числам, ни по падежам_
* [x] **_5_**: `arguments definitions` => `argument definitions`
* [x] **_125_**: `arguments division` => `argument division`
* [x] **_432_**: `programs fields` =>  `program fields`

### refal-5-lambda/doc/5-to-basis/README.en.md

* [x]  **_10_**: `a metafunctions` => `a metafunction` or `metafunctions` (артикль _a_ употребляется только с единственным числом)

### refal-5-lambda/doc/historical/note000.en.md

* [x] **_18_**: ` all functions ... appears to be external` => `all functions ... appear to be external` (functions - множественное число)
* [x] **_129_**:` allow not only to reduce` => `allow not only reducing` (правило: allow + объект + инфинитив или allow + герундий)
* [x] **_339_**: `leters` => `letters` (неправильное написание слова)
* [x] **_344, 380, 641_**: `lexems` => `lexemes` (неправильное написание слова)
* [x] **_375_**: `the sets to handler functions is not transmitted `=> `the sets to handler functions are not transmitted` (sets - множественное число)
* [x] **_378_**: `An method` => `A method` (неправильное использование артикля)
* [x] **_378_**: `analisator` => `analyzer` (слова _analisator_ не существует)
* [x] **_382_**: `lexem` => `lexeme` (неправильное написание слова)
* [x] _**385**_: `while I were` => `while I was` (I - единственное число)
* [x] **_389_**:  `commands sequence` =>  `command sequence`  (Правило: _прилагательные в английском языке не изменяются ни по родам, ни по числам, ни по падежам_)
* [x] **_396_**:  `all the file pathes` => `all the file paths`(неправильное написание слова "путь")
* [x] **_417_**:  `could be interpretated` =>  `could be interpreted` (неправильное написание слова)
* [x] **_439_**: `Those classes corresponds` => `Those classes correspond` (classes - множественное число)
* [x] **_448_** : `programing` => `programming` (неправильное написание слова)
* [x] **_519_**: ` I didn’t done` =>  `I didn’t do` (Past Simple Tense)

**Comment by Mazdaywik** [comment]
4+3+1+15 = 23
