### ISSUE TITLE
Исправление ошибок

### ISSUE THREAD

**Issue by torrentino555** [bmstu-iu9/refal-5-lambda#223]
Файл **note003.en.md**
* [x] 104:` then the correctness of the use of the variables is checked `заменить на `then the correctness of the use of the variables are checked` (множественное число)
* [x] 159:  `an allox array` заменить на ` an alloc array`
* [x] 738: `functions provides` заменить на `functions provide`(множественное число)
* [x] 754: `list of the contents of the closure are broken` заменить на `list of the contents of the closure is broken` (должно быть единственное число)
* [x] 781: `structur (and ATD-) brackets` заменить на `structural (and ATD-) brackets` (неправильное написание слова "структурный")

Файл **note003.txt** (все ошибки связаны с неправильным написанием)
~~77:` образецы` заменить на `образцы`~~
~~80: `генерится` заменить на `генерируется`~~
~~90: `сбаллансированности` заменить на `сбалансированности`~~
~~286:` Рассмотрем` заменить на `Рассмотрим`~~
~~419: `несущественнен` заменить на `несущественен`~~
~~619, 657, 658: `двусвязанный` заменить на `двусвязный`~~

Файл **note001.txt** (все ошибки связаны с неправильным написанием)
~~17: `Ввводим` заменить на`Вводим`~~
~~73: `может зависить` заменить на `может зависеть`~~

Файл **3-basics.en-alt.md**
* [x] 256: `greatgrandmother` заменить на `great-grandmother`

**Comment by Mazdaywik** [comment]
Историческая документация `note???.txt` правкам не подлежит.

**Comment by Mazdaywik** [comment]
А её переводы — подлежат.
5+1 = 6
