### ISSUE TITLE
Ошибки [2]

### ISSUE THREAD

**Issue by torrentino555** [bmstu-iu9/refal-5-lambda#224]
Файл **note000.en.md**

1. 543:  `Inputing` заменить на ` Inputting` (неправильное написание)
1. 544: `functions to language is ideologically disgusting` заменить на `functions to language are ideologically disgusting` (множественное число)
1. 544: `because the functions is related`  заменить на `because the functions are related` (множественное число)
1. 548: `there is too absent built-in functions ` заменить на `there are too absent built-in functions` (множественное число)
1. 610: `will be much easyer` заменить на `will be much easier` (неправильное написание слова)
1. 625:  `The exception was only symbol table, which consist of ` заменить на `The exception was only symbol table, which consists of ` (единственное число)
1. 631:  `transmition`  заменить на `transmission` (неправильное написание слова)
1. 634: `sentences parts` заменить на `sentence parts` (прилагательные не изменяются по числам)
1. 637: `imposible` заменить на`impossible` (неправильное написание слова)
1. 653: `Nodes includes` заменить на` Nodes include `(множественное число)
1. 661:  `will be putted ` заменить на  `will be put` (формы глагола put: base form = put, вторая форма = put, третья форма = put)
1. 701: `the  list parts with rebuilded elements transmits` заменить на `the  list parts with rebuilded elements transmit `(множественное число)
1. 712:  `trasmiting` заменить на   `trasmitting` (неправильное написание слова)
1. 1256: `variables are largely similar with functions` заменить на `variables are largely similar to functions`
1. 1265: `the same operation(...) are executed repeatedly` заменить на` the same operation(...) is executed repeatedly` (единственное число)

**Comment by Mazdaywik** [comment]
15 ошибок, я вчера их не заметил. Жалко. 77+15 = 92. Уже поздно. ☹

**Comment by torrentino555** [comment]
> 15 ошибок, я вчера их не заметил. Жалко. 77+15 = 92. Уже поздно. ☹

А можно передать эти 15 баллов Варваре Соболевой, чтобы не пропадали?

**Comment by Mazdaywik** [comment]
Она эти ошибки может исправить. Пулл-реквесты она делать умеет:

* https://github.com/bmstu-iu9/utp2017-4-forum/pull/7
* https://github.com/bmstu-iu9/utp2017-4-forum/pull/8
* https://github.com/bmstu-iu9/utp2017-4-forum/pull/29

**Comment by Mazdaywik** [comment]
Она может исправить и другие ошибки, найденные Вами и @kategimranova.
