### ISSUE TITLE
Предупреждать об экранируемых предложениях

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/refal-5-lambda#256]
Мотивация
========

Задача состоит в том, чтобы обнаруживать в функциях предложения, которые никогда не выполняются, и сообщать о них пользователю (выдавать предупреждения).

Предложение в программе может не выполняться, если его левая часть (образец+условия) описывает множество аргументов, являющихся подмножеством другого предложения, записанного выше. В таких случаях мы будем говорить что одно предложение экранирует другое.

Случай, когда не выполняется правая часть предложения с условием, сложен для автоматического анализа. Более того, такие предложения могут быть написаны намеренно ради побочного эффекта в условии и отката на последующие предложения.

Поэтому будем рассматривать случаи, когда экранирующие предложения условий не содержат. (Впрочем, условия вида `, A : B` тоже можно обнаруживать, но они к данной задаче не относятся.)

Экранирующие предложения такого вида могут быть написаны только по ошибке, и эта ошибка может быть достаточно коварной (не очевидной). Но при этом её вполне можно диагностировать автоматически и выдавать соответствующее предупреждение.

Для L-образцов всё довольно просто, для образцов общего вида проверить вложения — задача нетривиальная. И тут нам потребуется консультация Антонины Николаевны (@TonitaN), которая уже давно исследует этот вопрос в рамках написания модельного суперкомпилятора [MSCP-A](https://github.com/TonitaN/MSCP-A).

<details><summary>Старая мотивация ставила задачу оптимизации. Это сравнительно глупо (см. комментарии), поэтому она свёрнута.</summary>

Задача состоит в том, чтобы обнаруживать в функциях предложения, которые никогда не выполняются, и их удалять.

Конечно, программисты редко пишут функции с лишними предложениями, и, если пишут, то как правило по ошибке. Но всё становится интереснее, когда работает оптимизация, особенно, прогонка (для специализации мне это пока не очевидно).

Например:
```Refal5
Test {
  e.X = <CheckAB <ReplaceAB e.X>>
}

$DRIVE CheckAB, ReplaceAB;

CheckAB {
  A B e.X = FALSE;
  e.X = TRUE;
}

ReplaceAB {
  A B e.X = AB e.X;
  e.X = e.X;
}
```
Функция `CheckAB` проверяет, начинается ли аргумент на символы `A B`, `ReplaceAB` заменяет пару символов `A B` в начале аргумента на один символ `AB`. В идеале, в оптимизированном дереве вообще не должно быть символа `FALSE`. Но он есть:
```Refal5
Test {
  A B e.0#0 = TRUE;
  A B e.0#0 = FALSE;
  e.X#1 = TRUE;
}
```
Очевидно, второе предложение экранируется первым.

В чём преимущества исключения лишних предложений? Во-первых, уменьшается объём кода. Это ускоряет последующие проходы после оптимизации дерева и может ускорить весь процесс компиляции (поскольку чистка предложений сама требует времени). Это уменьшает объём исполнимого файла, а значит, он потенциально лучше будет влезать в кэш процессора. Во-вторых, оптимизатор совместного сопоставления с образцом может для таких случаев сгенерировать более эффективный код (ну, наверное, может).

</details>

Реализация
========
Нужна функция, которая принимает пару образцов и определяет, является ли первый подмножеством второго. На первом этапе можно использовать функцию обобщённого сопоставления — если сопоставление чистое, то образец точно вкладывается. Но вообще задача сложнее, @TonitaN не даст соврать.

~~Побочная задача~~
================

<details><summary>Задача неактуальна, обоснование в комментариях. Поэтому свёрнуто.</summary>

Оптимизатор при преобразованиях сохраняет область определения программы: если исходная функция падала на некотором аргументе, то и преобразованная функция будет падать. Например:
```Refal5
Test {
  s.X = <F s.X>;
  t.X = Term;
}

$DRIVE F;

F {
  A = Symbol A;
  B = Symbol B;
}
```
Если аргументом функции `Test` является один из двух символов `A` или `B`, то функция вернёт или `Symbol A`, или `Symbol B`, соответственно. Если любой другой символ — функция упадёт. Если не символ (круглые или квадратные скобки) — функция вернёт `Term`.

Прогонка функции `F` по Турчину (см. «Эквивалентные преобразования…», 197? год) расширит область определения — на любых символах, кроме `A` и `B`, функция будет выдавать `Term`.

Чтобы избежать такого искажения программы, компилятор добавляет вызов пустой функции:
```Refal5
Test {
  A = Symbol A;
  B = Symbol B;
  s.X#1 = <F*2 s.X#1>;
  t.X#1 = Term;
}

F*2 {
}
```
Компилятор добавил третье предложение, которое срабатывает, когда аргумент функции `Test` является любым символом, кроме `A` и `B`. В нём вызывается пустая функция `F*2`, которая падает на любом аргументе. Таким образом, область определения сохраняется.

**Но есть случаи, когда такие предложения избыточны.** Модифицируем функцию `Test` таким образом (функция `F` та же):
```Refal5
Test {
  1 s.X = <F s.X>;
  2 t.X = Term;
}
```
Оптимизированное дерево примет вид:
```Refal5
Test {
  1 A = Symbol A;
  1 B = Symbol B;
  1 s.X#1 = <F*2 s.X#1>;
  2 t.X#1 = Term;
}

F*2 {
}
```
Третье предложение можно смело исключить — область определения программы не изменится.

Избыточные «аварийные» предложения выявляются тем же механизмом. Если образец «аварийного» предложения вкладывается в один из последующих образцов, то «аварийное» предложение исключать нельзя. Иначе — можно.

Однако, следует иметь ввиду, что режекция аварийных предложений может затруднить отладку, т.к. оптимизируемая программа будет падать на один шаг раньше. Не «очищенная» программа падала на функции `F*2`, которая вызывалась с тем же аргументом, что и функция `F` в исходной программе. «Очищенная» программа будет падать сразу в функции `Test`. Поэтому, в отличие от устранения экранированных предложений, устранение аварийных предложений должно контролироваться пользователем.

</details>

**Comment by Mazdaywik** [comment]
Задача достаточно интересная для курсовой работы. По тонким вопросам экранирования с образцами общего вида нас согласилась консультировать @TonitaN.

**Comment by Mazdaywik** [comment]
Задача не была выбрана в качестве курсовой.

**Comment by Mazdaywik** [comment]
Побочная задача про удаление избыточных аварийных предложений сомнительна. Аварийные предложения в программе или должны быть (для надёжности), или их быть не должно (для быстродействия).

Отладочная версия программы должна содержать все аварийные предложения для облегчения отладки. Если удалять некоторые с сохранением области определения — программа продолжит падать (выявлять ошибки), но они будут возникать в неожиданных местах. Придётся или изучать лог компиляции, или пересобирать и запускать отладочную версию программы.

Будет ли программа без аварийных предложений существенно быстрее программы с ними? Можно предположить, что наверное. Аварийные предложения в корректной программе никогда не выполняются. При отключенной оптимизации совместного сопоставления с образцом (`-OP`) «бесполезные» образцы никогда не будут проверяться.

При включенной `-OP` их влияние уже будет меньше, поскольку (а) прогонка выполняется только для L-образцов, (б) аварийные предложения являются обобщениями предшествующих предложений — результатов прогонки. Поэтому если будет выделена (а скорее всего будет) группа предложений, соответствующих результатам прогонки, их ГСО будет включать образец аварийного предложения, и либо аргумент ему соответствует и управление передаётся на одно из корректных предложений, либо аргумент ему не соответствует вообще.

Т.е. аварийные предложения при включённой `-OP` на быстродействие влиять не должны. А влияние на отключённую оптимизацию ещё надо выяснить профилировщиком. Релизная версия программы будет собираться, скорее всего, с `-OP`, поэтому отключать аварийные предложения для неё может быть менее актуально.

Можно предположить, что при отключении аварийных предложений ГСО для оставшихся образцов может быть вычислено иначе и оптимальнее, но это не очевидно.

Поэтому смысла в выборочном удалении аварийных предложений нет никакого. В отладочной версии затрудняет отладку, на быстродействие влияет мало, реализовывать его сложно. Поэтому побочная задача закрывается.

**Comment by Mazdaywik** [comment]
Да и основная задача сомнительна.

Да, прогонка может привести к появлению экранируемых предложений. Но их наличие ещё нужно доказать — предъявить образцы кода, где такие предложения есть. Пример в «Мотивации» надуманный — никто не планирует использовать Рефал-5λ как инструмент для задач верификации. А второе предложение может быть удалено как побочный результат оптимизации сопоставления с образцом (см.<span>&nbsp;</span>#182). Да и без удаления при использовании имеющейся оптимизации `-OP` второе предложение почти не потребует накладных расходов.

Но вот что важно. **Экранируемое предложение в исходном коде — это ошибка программиста.** Намеренно писать такие предложения бессмысленно (разве что как грязный хак в процессе отладки, да и то я так не делал), они могут быть написаны только случайно по ошибке.

А это значит, что в программе появилось предложение, которое сокрывает все или несколько последующих, чего, скорее всего, программист не имел ввиду. И такую ошибку может быть довольно трудно найти!

Поэтому предлагается изменить мотивировку — **не удаление для оптимизации, а диагностика потенциальной ошибки!** Компилятор должен находить экранируемые предложения и о них сообщать пользователю.

**Comment by Mazdaywik** [comment]
При выполнении этой задачи нужно будет сделать два класса правок: **технические** и **содержательные.**

**Технические правки** касаются поддержки предупреждений в самом компиляторе. Дело в том, что на данный момент компилятор поддерживает только сообщения об ошибках, которые прерывают компиляцию. Нужно добавить сообщения-предупреждения, которые по умолчанию не прерывают компиляцию.

**Содержательные правки** относятся к теме работы — нужно для каждого предложения каждой функции проверять, нет ли предложения ниже, левая часть которого является частным случаем левой части рассматриваемого предложения.

Детали содержательных правок обсудим позже, в этом комментарии я опишу технические правки, которые нужно выполнить.

Поддержка предупреждений в компиляторе
==============================
Обработка ошибок в компиляторе
----------------------------------------
Лексические ошибки лексические анализаторы (Простого Рефала и Рефала-5λ) просто возвращают как особую лексему `TkError`. Синтаксические анализаторы об этой лексеме даже не задумываются, просто вызывают `AddUnexpected` (Простой Рефал) или `UnexpectedToken` (Рефал-5λ). Если неожиданным токеном оказывается `TkError`, то добавляется сообщение об ошибке из атрибута `TkError` вместо ошибки «неожиданный токен, ожидалось что-то другое».

Синтаксические и семантические ошибки накапливаются в списке ошибок — объекте `t.ErrorList`. Это терм абстрактного типа данных, содержимое доступно только файлу `Error.ref`, вне этого файла он может сопоставляться только с t-переменной. В файле `Error.ref` описано несколько методов доступа к содержимому файла.

Проходы контекстно-свободного синтаксического анализа (`SR-Parser.sref`, `R5-Parser.sref`) принимают на входе список токенов и список ошибок, на выходе строят дерево и возвращают пополненный список ошибок. Они обнаруживают только ошибки контекстно-свободного синтаксиса.

Семантические (контекстно-зависимые) ошибки обрабатываются в проходе `Checker.ref`, который принимает список ошибок и дерево и возвращает пополненный список ошибок.

Все проходы компилятора последовательно вызываются в `Engine.ref`, этот же файл отвечает за обработку директивы `$INCLUDE` — вставку заголовочных файлов. Здесь нам интересно, что в `Engine.ref` проверяется, список ошибок пустой или нет.

Есть одна ошибка, которая обнаруживается при генерации кода (генерация команды перехода на адрес дальше 65535), в этом случае компиляция аварийно прерывается. Эта ошибка здесь нам совершенно не интересна, просто дана для полноты картины.

Как добавить предупреждения
------------------------------------
Предупреждения нужно добавлять не просто так, а с возможностью управления ими через интерфейс командной строки.

Интерфейс предлагается позаимствовать у GCC. У него есть опция `-W`, принимающая строковой параметр. Этот параметр может быть или именем предупреждения (`-Wmissing-braces`), или уровнем предупреждений (`-Wpedantic`, `-Wall`, `-Wextra`), или управлять реакцией на предупреждения (`-Werror` считает предупреждения за ошибки). Ещё вроде чтобы отключить предупреждение, можно записать `-Wno-…`, где вместо многоточия имя предупреждения. Подробнее о предупреждениях GCC можно прочитать здесь:

<https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html>

Обработкой командной строки занимаются `ParseCmdLine.ref` (разбирает опции) и `Config.ref` (`t.Config`, объект конфигурации).

Предупреждение настоящей задачи будет называться `-Wscreening`, по умолчанию должно быть отключено. Может включаться как ключом `-Wscreening`, так и ключом `-Wall`. Ключ `-Werror` предписывает считать все предупреждения ошибками, он тоже должен поддерживаться (удобно будет в автотестах).

Поскольку анализ экранирования предложений затратен по времени, он должен включаться только если явно задан в командной строке.

**Comment by Mazdaywik** [comment]
У сообщения компилятора должна быть координата. Координата предупреждения об экранировании — координата определения самой функции. Для того, чтобы указывать координаты самих предложений, нужно менять синтаксическое дерево, а значит немалую часть кода компилятора, работающего с ним. А координата определения функции уже есть в самом узле функции.

Э-э-э. А координата определения функции уже есть в самом узле функции. Шиш. Только у глобальных функций, у блоков и вложенных функций координаты нет.

Или всё-таки менять дерево, добавляя к предложениям их координаты (править оба парсера, `Engine.ref`, `Checker.ref` и немного `Desugaring.ref`), или выдавать корявые сообщения об ошибках.

Придётся расширять дерево…

**Comment by nexterot** [comment]
Коммиты 6b5025e и a350be0 созданы по ошибке.

**Comment by nexterot** [comment]
😌 😌 😌
