### ISSUE TITLE
Логотип

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/refal-5-lambda#268]
Мотивация
========
Проекту нужен логотип. Идейно — в наше хипстерское время логотипы есть не только у языков программирования, но и у самых занюханных библиотек. Технически — нужна иконка для инсталлятора, файлов исходного текста и favicon для сайта с документацией.

Обзор имеющихся логотипов
====================

Иконки для Рефала-5λ или Простого Рефала
---------------------------------------------------

Технически сейчас инсталлятор иконку имеет, но она сделана тупо из скриншотов текстового редактора:

![иконка](https://raw.githubusercontent.com/bmstu-iu9/refal-5-lambda/8f1cd5dd68985715dc3c625048673cd187356130/make-setup/icon.ico)

Иконку делал я, и поскольку рисовать не умею, сделал тупо скриншот с кодом. Входящие в её состав иконки разного разрешения:

![icon16](https://user-images.githubusercontent.com/1309859/75271462-4d204100-580d-11ea-9d8a-c6082dc8cb9c.png)
![icon16-2](https://user-images.githubusercontent.com/1309859/75271466-4db8d780-580d-11ea-8b65-3bed129df3e6.png)
![icon32](https://user-images.githubusercontent.com/1309859/75271468-4e516e00-580d-11ea-9dd2-d8ba14915678.png)
![icon32-2](https://user-images.githubusercontent.com/1309859/75271472-4e516e00-580d-11ea-8c3b-3b65b1aa0bf3.png)
![icon32-3](https://user-images.githubusercontent.com/1309859/75271474-4f829b00-580d-11ea-969e-f06d8e8edb1e.png)
![icon48](https://user-images.githubusercontent.com/1309859/75271476-4f829b00-580d-11ea-9f33-54e7fec89438.png)
![icon64](https://user-images.githubusercontent.com/1309859/75271479-4f829b00-580d-11ea-8705-254088eb0ec9.png)
![icon256](https://user-images.githubusercontent.com/1309859/75271482-501b3180-580d-11ea-93b7-260613a5249d.png)

В плагине [RefalFiveLambdaPlugin](https://github.com/bmstu-iu9/RefalFiveLambdaPlugin) в качестве иконки для файлов используется баночка с шариками:

![баночка](https://raw.githubusercontent.com/bmstu-iu9/RefalFiveLambdaPlugin/b2215bf1270130986dded736ea28027a31859552/src/ru/tereshkina/plugin/icons/jar-gray.png)

Чем мотивировала её автор плагина Дарья Терёшкина (@BuDashka), я так и не понял.

В плагине [simple-refal-plugin](https://github.com/bmstu-iu9/simple-refal-plugin) используется иконка пчелы:

![пчёлка](https://raw.githubusercontent.com/bmstu-iu9/simple-refal-plugin/master/src/ru/barashko/simplerefalplugin/icons/bee.png)

Я спросил автора плагина Владимира Барашко (@vbarashko): «А почему пчёлка?» Он ответил «А почему бы и нет». Мне нечего было возразить.

Даниил Гавриловский (@GDVFox) разработал [раскраску синтаксиса](https://marketplace.visualstudio.com/items?itemName=gdvfox.refal-5-lambda) для Visual Studio Code, в ней он использовал следующий логотип:

![логотип Гавриловского](https://raw.githubusercontent.com/GDVFox/vscode-refal-5-lambda/master/images/icon.png)

Иконка неплохая, но [шаблонная](https://yandex.ru/images/search?cbir_id=3075952%2Fj_653hX-qyF4U0XkEgGvpw&url=https%3A%2F%2Fraw.githubusercontent.com%2FGDVFox%2Fvscode-refal-5-lambda%2Fmaster%2Fimages%2Ficon.png&rpt=imagelike&lr=213) и поэтому безликая.

Логотипы к другим Рефалам
---------------------------------
Сайт http://refal.ru:

![refal.ru](http://refal.ru/images/refal-81.jpg)

Favicon страницы Рефала-5 http://www.botik.ru/pub/local/scp/refal5/

![Рефал-5](http://www.botik.ru/pub/local/scp/refal5/pic/P5.jpg)

Иконка для редактора [Refal Sci-TE](http://www.refal.net/~belous/refscite.htm):

![Refal Sci-TE](http://refal.ru/~belous/images/refscite.jpg)

Иконки Рефала+ (с сайтов http://rfp.botik.ru и http://wiki.botik.ru/Refaldevel соответственно):

![rfp.botik.ru](http://rfp.botik.ru/_/rsrc/1232045384417/config/app/images/customLogo/customLogo.gif)
![wiki.botik.ru/Refaldevel](http://wiki.botik.ru/twiki/pub/Refaldevel/WebPreferences/refal-plus-logo-2-50x50.png)

Логотип проекта https://github.com/cmc-msu-ai/refal

![cmc-msu-ai/refal](https://camo.githubusercontent.com/fbd57ad78faa553311f8a2ee5dbd4cc35901abab/687474703a2f2f726566616c322e6769746875622e696f2f696d616765732f726566616c325f6c6f676f2e706e67)

Требования к иконке
==============
Идейные требования
------------------------
Идейных требований пока нет.

Технические требования
----------------------------
* Должны поддерживаться стандартные размеры иконок Windows: **16×16, 32×32,** 48×48, 64×64, 256×256. Мелкие, наверное, нужно будет подгонять вручную, а крупные можно смасштабировать.
  Крайне желательно иконки перечисленных размеров объединить в одну многостраничную иконку.
* Логотип для инсталлятора размером 93×302 в формате BMP. Текущий логотип — тоже [скриншот](https://github.com/bmstu-iu9/refal-5-lambda/blob/master/make-setup/logo.bmp).
* Нужен баннер в README.md как у https://github.com/cmc-msu-ai/refal. Размер баннера 800×180, размер файла не более 100 Кбайт.
* У логотипа должна быть как кириллическая версия (слово _Рефал_ русскими буквами), так и латиницей (слово _Refal_ латинскими).

Других технических требований пока нет. Если вспомню, напишу.

**Comment by BokarevDmitry** [comment]
> Есть два варианта: #295 и<span>&nbsp;</span>#296, оба интересные. Какой мне теперь выбрать?

Выбирайте сердцем!

**Comment by Mazdaywik** [comment]
* За<span>&nbsp;</span>#296 — логотип @BokarevDmitry уже два голоса: @AleksMa и @BokarevDmitry 😃.
* За<span>&nbsp;</span>#295 — логотип @SpeedyGonzaless пока голосов нет.

**Comment by Mazdaywik** [comment]
@bmstu-iu9/utp-2017, @bmstu-iu9/utp-2018 можете тоже проголосовать 😃.

**Comment by GDVFox** [comment]
+1 за https://github.com/bmstu-iu9/refal-5-lambda/pull/296 :)

**Comment by anyasinyavskaya** [comment]
#296

**Comment by Kodonomo** [comment]
#296

**Comment by Apakhov** [comment]
Против всех. Решение обосновано снятием с голосования логотипа от @GDVFox , кандидата от народа

**Comment by BokarevDmitry** [comment]
> Против всех. Решение обосновано снятием с голосования логотипа от @GDVFox , кандидата от народа

Однако сам @GDVFox уже проголосовал 😉

**Comment by StructDeStruct** [comment]
\+ за #296

**Comment by Apakhov** [comment]
> Однако сам @GDVFox уже проголосовал 😉

Выбрал меньшее из двух зол

**Comment by TSARukyanGT** [comment]
#296

**Comment by nexterot** [comment]
Пойду против системы
#295

**Comment by Mazdaywik** [comment]
Я буду считать голоса вот здесь:
![image](https://user-images.githubusercontent.com/1309859/85919773-20417080-b877-11ea-9a5f-b9c589cdace8.png)

Чтобы проголосовать, нужно добавить реакцию здесь:
![image](https://user-images.githubusercontent.com/1309859/85919808-60085800-b877-11ea-9d1e-c50acf87035f.png)

**Comment by Mazdaywik** [comment]
@Apakhov:
> Против всех. Решение обосновано снятием с голосования логотипа от @GDVFox , кандидата от народа

Я не возражаю и против логотипа @GDVFox, только для него нужно создать pull-request и набор картинок (иконки всех размеров + [картинку для инсталлятора 93×302](https://user-images.githubusercontent.com/1309859/84884533-8c172280-b09a-11ea-9986-247b6233168f.png) + баннер для README).

**Comment by Mazdaywik** [comment]
* За логотип @SpeedyGonzaless’а (#295) проголосовал только @nexterot.
* За логотип @BokarevDmitry (#296) проголосовали @AleksMa, @BokarevDmitry (не считается), @GDVFox, @saskamegaprogrammist, @IgorZobnev, @kategimranova, @masyagin1998, @VladisP, @anyasinyavskaya, @kirsnegir, @StructDeStruct (это всё лайки).

Два голоса GitHub не показал **(среди них мой):**
![image](https://user-images.githubusercontent.com/1309859/86506358-592d9800-bdd7-11ea-9836-833ecb81193c.png)
В комментариях ещё проголосовал @TSARukyanGT.

В общем, большинством голосов выбираем #296!

**Comment by nexterot** [comment]
`За логотип @SpeedyGonzaless’а (#295) проголосовал только @nexterot.`

![image](https://user-images.githubusercontent.com/21362190/86506494-6c8d3300-bdd8-11ea-8094-39e9745836a0.png)

**Comment by Mazdaywik** [comment]
Влил оба пулл-реквеста, смог увидеть файлы.

В общем, оба логотипа коту под хвост.
* У @SpeedyGonzaless на маленьких иконках буква λ красного цвета, на крупных — жёлтого. И непонятно, это недоработка или так и должно быть.
* У @BokarevDmitry иконки не того размера:
  ![image](https://user-images.githubusercontent.com/1309859/86531731-74c69a80-becc-11ea-9cea-e58174728400.png)
  Как иконка 32×32 может быть размером (см. снизу слева) 134×134! И размеры не выдержаны у всех иконок, кроме 256×256.
  И если иконку масштабировать на правильный размер, то её качество ухудшается.

Халтурщики оба.

**Comment by Mazdaywik** [comment]
Откатываю последние пять коммитов до b40f74f05126a2232ad113df040de5748f4059f9, эта чушь мне в истории не нужна.

**Comment by Mazdaywik** [comment]
Уточнил технические требования. Логотипы в pull request’ах (которые надо было отклонить, а я по глупости влил, а потом откатывал) этим техническим требованиям не удовлетворяли.

**Comment by Mazdaywik** [comment]
@SpeedyGonzaless, @BokarevDmitry, если не хотите, чтобы Ваша работа пропала даром, можете подогнать свою работу под уточнённые технические требования и открыть новые pull request’ы.

**Comment by Mazdaywik** [comment]
> чушь мне в истории не нужна.

@SpeedyGonzaless, @BokarevDmitry, прошу прощения за то, что в комментарии выше написал «чушь». Написал на эмоциях. На самом деле, я откатил коммиты, т.к. они сильно утяжеляли репозиторий, примерно на 1 или 2 мегабайта, не помню. А он и так долго клонируется (скорость на клонирование у GitHub низкая). Поэтому я обрезал историю только по техническим причинам, а не из-за плохих логотипов. Были бы файлы лёгкими (десятки-сотни килобайт), откатывать не стал бы, сложил бы в папку, но не использовал.

**Comment by Mazdaywik** [comment]
@BokarevDmitry, у Вас получился неплохой логотип. Осенью я Вам на почту написал технические замечания по нему. Поправьте их, пожалуйста, и открывайте pull request, а то потом может быть поздно. Нынешние третьекурсники могут предложить новый вариант логотипа, который я приму. Жалко будет Вашу работу, она неплохая.

**Comment by Mazdaywik** [comment]
Реализовано в #357.
