### ISSUE TITLE
Условное сопоставление по образцу

### ISSUE THREAD

**Issue by basp1** [bmstu-iu9/refal-5-lambda#275]
Добрый день!

Например, в языке Erlang есть такое понятие как "гарды". Они позволяют применить то или иное правило в зависимости от выполнения определенных условий (т.е. в примере часть после "when"):
```
display(N) when N > 10 ->   
   io:fwrite("greater then 10"); 
display(N) when N < 10 -> io:fwrite("Less 
   than 10").
```
Возможно ли такое сделать в рефале? Т.е. чтобы сопоставление по образцу успешно проходило не только при условии соответствия констант и s,t,e переменных, но и при выполнении условия - результаты вызова пользовательской функции?
Т.е. что-то вроде
```
Func {
  s.1 {> s.1 10} = 'greater 10';
  s.1 = 'less than 10';
}
```
Я понимаю, что это можно выразить и без использования подобных "гардов" (предусловий), но такой подход кажется более читабельным.

Собственно, вопросы такие. Есть ли такие конструкции в рефале? Если нет, то можно ли их добавить? Или это совершенная глупость и противоречит идеологии языка?

**Comment by basp1** [comment]
Удалить

**Comment by Mazdaywik** [comment]
Удалить не могу. Могу только перенести в другой репозиторий или запинить.
![Удалить не могу](https://user-images.githubusercontent.com/1309859/78257140-20dd9b80-7502-11ea-9c2d-e302e5e10147.png)

**Comment by Mazdaywik** [comment]
В Рефале-5 (и в его расширении Рефале-5λ) такая конструкция есть и называется _условие_ или _where-конструкция_ (термин из учебника Турчина, почти никто не использует).

В Рефале-6 и Рефале Плюс понятие условия обобщено до понятия неуспеха. Можете почитать [учебник по Рефалу-6](http://refal.ru/~arklimov/refal6/index.html), он попроще Рефала Плюс. Концепция неуспехов она посложнее и довольно интересна сама по себе. Но добавлять её в Рефал-5λ я не планирую.
