### ISSUE TITLE
Неправильная подсветка синтаксиса.

### ISSUE THREAD

**Issue by Cstyler** [bmstu-iu9/refal-5-lambda#288]
При использовании звёздочки в качестве идентификатора функции умножения, подсветка показывает, что справа комментарий. Подсветку устанавливал плагином в Visual Studio Code.
![Screenshot from 2020-05-21 21-37-18](https://user-images.githubusercontent.com/16050179/82593653-83225680-9bab-11ea-8491-785dc4781731.png)

**Comment by Mazdaywik** [comment]
Подсветку делал Даниил Гавриловский (@GDVFox), он её поддерживает в репозитории расширений VS Code.

**Comment by GDVFox** [comment]
Починил в https://github.com/GDVFox/vscode-refal-5-lambda/pull/1, можно обновлять расширение и проблема исчезнет.

**Comment by Mazdaywik** [comment]
@Cstyler, теперь работает?

**Comment by Mazdaywik** [comment]
Должно работать.

**Comment by Cstyler** [comment]
Работает
