### ISSUE TITLE
Зачем нужны bat/shell скрипты?

### ISSUE THREAD

**Issue by ponyatov** [bmstu-iu9/refal-5-lambda#293]
make прекрасно определяет ОС, есть условные блоки

```make
OS ?= $(shell uname)

# all:
# 	echo Read Makefile for details

ifeq ($(OS),Windows_NT)

# all-win:
all:
#	bootstrap.bat --no-tests
	OS=$(OS) $(MAKE) -f bootstrap.mk build

test:
	OS=$(OS) $(MAKE) -f bootstrap.mk test

# libs-win:
libs:
	cd src\lib && make.bat
endif

ifeq ($(OS),Linux)

# all-posix:
all:
	./bootstrap.sh --no-tests
endif
```

**Comment by Mazdaywik** [comment]
Какая именно Make? Make от Borland? WMake от Watcom? NMake от Microsoft?

**Comment by ponyatov** [comment]
RMake на РЕФАЛе, под win есть MinGW с GNU Make

**Comment by Mazdaywik** [comment]
Уже есть `rlmake` на Рефале-5λ, она используется в дистрибутиве, но она пока довольно ограничена. Приоритетная цель у меня — развитие языка и компилятора, а не системы сборки.

Фиксация какой-то конкретной системы сборки повышает требования к окружению.

Сейчас это требования: **Windows NT** (т.е. 9x/ME не поддерживаются), **Linux** последних нескольких лет (на Fedora 16 есть проблемы со сборкой) или **macOS** (собирал не я, но работало) + наличие какого-то компилятора **C++98.**

Если мы зафиксируем какую-то утилиту сборки (диалект make от одного из сишных компиляторов), ANT, Maven, CMake, то в требованиях к окружению появится эта система сборки. Возможно, оптимальный вариант — это перейти на CMake, но объём работы меня пугает.

Скрипты на .bat и Bash у меня отчасти по историческим причинам — если всё работает, то зачем всё менять (тем более, что это не приоритетно).

> На самом деле все перечисленные должны быть полностью совместимы между собой на уровне базового функционала — правил и переменных. Если не пользоваться специфическими расширениями, не важно какая версия `make` используется.

Я глубоко не изучал синтаксис make разных поставщиков. Возможно, простые скрипты сборки можно делать переносимыми между всеми, но это может оказаться сильно ограниченным подмножеством, например, в нём может не быть условных блоков. Кроме того, могут вылезать нюансы с различным поведением одного и того же синтаксиса.

Поэтому сопровождать 2 параллельных скрипта .bat + Bash мне представляется менее затруднительным, чем несколько разных makefile’ов.

К слову, `uname` требует установленного MSys, если ставить MinGW Builds (знаю, что они устарели), то вызовы `$(shell uname)` в скриптах работать не будут.

**Comment by Mazdaywik** [comment]
Если речь идёт только о файле `Makefile` в корне, то его цель — запуск сборки из среды IntelliJ IDEA. Для этой среды есть плагин Рефала-5λ, поддерживающий подсветку синтаксиса, синтаксических ошибок и имеющий семантическое автодополнение. Но IDEA умеет собирать только проекты на Java. Плагин для GNU Make позволяет запускать цели в Makefile’ах, но не как цели сборки, а как цели для запуска. Им я и пользуюсь, чтобы не переключаться на консоль для перекомпиляции компилятора.

**Comment by Mazdaywik** [comment]
Цели перейти со скриптов .bat и Bash на какую-то систему сборки сейчас не стоит. Поэтому закрываю заявку.

**Comment by ponyatov** [comment]
`make` tool official specification (IEEE Std 1003.1-2017 / POSIX.1-2017)
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html

**Comment by Mazdaywik** [comment]
Замечательно, только я не уверен, что этому стандарту следует nmake из Visual C++. А поддерживать несколько параллельных Makefile, ИМХО, сложнее, чем поддерживать пару параллельных скриптов .bat и .bash.
