### ISSUE TITLE
Профилировщик функций считает развёртывания замыканий за шаги

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/refal-5-lambda#316]
Профилировщик функций считает развёртывания замыканий за шаги. Но делать этого не должен, т.к. рефал-машина их как шаги не подсчитывает.

**Comment by Mazdaywik** [comment]
Всё не так просто. Нужно подсчитывать время развёртки замыкания, в том числе в средних шагах рефал-машины. Поэтому развёртки как шаги считать приходится. Так что это не бага, а фича.

Если программа делает 100500 вызовов функций, требующих развёртки замыкания с контекстом, то в логе должно быть 100500 развёрток (чтобы оценить время одной развёртки) и 100500 вызовов уже после развёртывания. И средний шаг должен считаться как общее время, делённое на количество вызовов и количество развёртываний.

С другой стороны, при оптимизации числа шагов (что нужно, если шагов слишком много и в лимит тест не влезает), псевдошаги-развёртки несколько сбивают с толка. Но пока я не придумал, что с ними делать.

**Comment by Mazdaywik** [comment]
@suova, можете посмотреть сообщение в коммите 568b5539? Что-то я сомневаюсь, что его грамотно написал.

**Comment by Mazdaywik** [comment]
@suova прокомментировала сам коммит:

> Я бы написала “including unwrapped closures”

**Comment by Mazdaywik** [comment]
Я имел ввиду: «Всего шагов (включая развёртывания замыканий)».

> Total steps (including unwrapped closures)

Это можно перевести как «Всего шагов (включая развёрнутые замыкания)», что немного не то.

Шаг вычисления — это замена скобок вызова `<F …>` на некоторый результат вычислений. Если вызывается не функция, а замыкание, то шаг выполняется в два этапа: сначала замыкание развёртывается — из объекта замыкания копируются значения связанных переменных, потом вызывается функция замыкания. Здесь эти два этапа одного шага считаются отдельно.

Возможно, упоминание шагов стоит вообще убрать и написать
```С++
"Function calls and closure unwrappings %.0f\n"
```
Но тогда непонятно, что написать в следующей строчке:
```C++
fprintf(profile, "Mean step time: %f us\n\n", 1000 * mean_step_time)
```
Ведь это среднее время от «полушагов». О! Полушаги!

**Comment by Mazdaywik** [comment]
@suova, а в этом коммите ↑ где я времена и залоги напутал?

**Comment by suova** [comment]
Здесь всё супер!

**Comment by Mazdaywik** [comment]
@suova, неожиданно!

Спасибо за помощь!

**Comment by Mazdaywik** [comment]
Это не бага, а фича.
