### ISSUE TITLE
Не работает определение палиндрома на Linux

### ISSUE THREAD

**Issue by inferrna** [bmstu-iu9/refal-5-lambda#365]
```Refal
/*
IsPalindrome {
      s.OneSymbol = "Found \""s.OneSymbol"\"";
       = "Found empty";
      s.Equal e.Middle s.Equal = <IsPalindrome e.Middle>;
      e.Other = "Not found \"" e.Other "\"";
    }
*/

IsPalindrome {
  s.OneSymbol = 'True';
  /* empty */ = 'True';
  s.Equal e.Middle s.Equal = <IsPalindrome e.Middle>;
  e.Other = 'False';
}


$ENTRY Go {
    = <Prout<IsPalindrome "ohaonnah">>
}
```
Выдаёт либо `True`, либо  `Found " ohaonnah "` (именно с пробелами возле кавычек) для закомментированной версии.
Система
```
Ubuntu 22.04.1 LTS
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
```

Дождался выполнения автотестов, они прошли.

**Comment by Mazdaywik** [comment]
В двойных кавычках записывается символ-слово (он же, составной символ), в одинарных — литера. Вы вызываете функцию `IsPalindrome`, передавая ей один символ. См. <https://bmstu-iu9.github.io/refal-5-lambda/B-reference.html#выражения>.
