### ISSUE TITLE
Рефал-5λ как интерпретатор

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/refal-5-lambda#48]
## Что имеем сейчас

Компилятор сейчас преобразует входной текст на Рефале в код на C++, а затем вызывает компилятор C++, который из оттранслированных файлов, файлов библиотеки стандартных функций и рантайма собирает экзешник.
### Преимущества такого подхода:
- самостоятельность исполнимых файлов — запуск программ не предполагает никаких требований к окружению,
- потенциально высокое быстродействие (в режиме прямой кодогенерации),
- простота реализации FFI — компилятор C++ не делает различия между файлами, скомпилированными на Рефале и написанными вручную.
### Недостатки:
- требования к окружению при компиляции — чтобы писать программы на Простом Рефале на машине пользователя должен быть установлен компилятор C++, причём различные компиляторы C++ имеют разный интерфейс командной строки, особенно под Windows,
- низкая переносимость — экзешник, скомпилированный под Linux, не будет работать под Windows,
- сложность в реализации таких возможностей как рефлексия, динамическая кодогенерация и загрузка модулей во время выполнения (такими возможностями наделены многие реализации, Турчин предполагал динамическую кодогенерацию в самой первой версии Рефала).
## Подход РЕФАЛа-5

Компилятор РЕФАЛа-5 `refc` порождает двоичные файлы на RASL’е, которые затем запускаются интерпретатором `refgo`.
### Преимущества
- минимум требований к окружению при компиляции — достаточно установить компилятор `refc`,
- простота процесса компиляции и запуска — нет никакого промежуточного компилятора C++,
- переносимость — `.rsl`-файлы одинаково работают на Windows и Linux.
### Недостатки
- замкнутость интерпретатора — программист ограничен набором встроенных функций, которые невозможно расширить без модификации компилятора и интерпретатора (именно это послужило причиной появления Модульного и Простого Рефалов),
- без интерпретатора скомпилированные файлы запустить невозможно.
## Цель

Предлагается совместить преимущества описанных подходов следующим образом:
- компиляция будет вестись в двоичные интерпретируемые файлы, компилятор C++ в большинстве случаев (исключение — см. далее) не нужен,
- двоичные интерпретируемые файлы прицепляются к интерпретатору как в случае с [SFX-архивами](https://ru.wikipedia.org/wiki/%D0%A1%D0%B0%D0%BC%D0%BE%D1%80%D0%B0%D1%81%D0%BF%D0%B0%D0%BA%D0%BE%D0%B2%D1%8B%D0%B2%D0%B0%D1%8E%D1%89%D0%B8%D0%B9%D1%81%D1%8F_%D0%B0%D1%80%D1%85%D0%B8%D0%B2) — получившиеся исполнимые файлы работают везде (исключение — см. далее),
- для реализации FFI предполагается добавить средства загрузки функций из .dll/.so. Вот для этого уже потребуется компилятор C++, скомпилированные программы будут нуждаться в данных dll-ках для запуска,
- также как SFX-архив можно просмотреть обычным архиватором без запуска, «самоинтерпретируемый RASL» можно будет запустить сторонним интерпретатором, например, на другой ОС,
- режим генерации интерпретируемого кода, на основе которого требуется реализовать эту задачу, ~~не намного медленнее режима прямой кодогенерации (замедление 20—30 %)~~ ~~намного медленнее. Цикл самоприменения с опцией `--gen=direct` быстрее (по чистому времени Рефала) чем `--gen=interp` в два раза, хотя шагов рефал-машины требуется только на 7 % больше.~~ не намного медленнее (цикл самоприменения с `--gen=both` с установленным и неустановленным `-DINTERPRET`, #67).

На данный момент уже реализован режим интерпретации (есть набор команд и их интерпретатор, см. [старую](https://github.com/Mazdaywik/simple-refal/blob/master/doc/historical/%D0%A0%D0%9F%D0%97.doc) и [новую](https://github.com/Mazdaywik/simple-refal/blob/master/doc/historical/%D0%94%D1%80%D0%BE%D0%B3%D1%83%D0%BD%D0%BE%D0%B2/index.pdf) записки).

Завершение задачи #46 также сильно упростит дальнейшую работу.

А вот задача #11 наоборот, несколько усложнит работу.
## Требуется:
- разработать формат интерпретируемых файлов (в которых будет храниться RASL и сопутствующая служебная информация),
- реализовать загрузчик этих интерпретируемых файлов в промежуточное представление в памяти,
- реализовать поддержку загрузки динамически загружаемых модулей (dynamic link libraries, shared objects) на платформах: Windows, Linux и OS X (хотя бы на первых двух),
- чтобы решение текущей задачи не конфликтовало с решением задачи #11.

**Comment by Mazdaywik** [comment]
Снял метку study, задачу буду делать сам.

**Comment by j123123** [comment]
Если используется подход с генерацией C++ кода из Рефал кода, то как в таком случае обеспечить возможность символьной отладки на уровне исходного кода рефала? Можно отлаживать сгенерированный С++ код, используя отладчик для C++, но тут надо будет еще понять, какому куску рефал-кода какой кусок C++ кода соответствует, что будет довольно неудобно.

**Comment by Mazdaywik** [comment]
@j123123, для отладки мне обычно хватает аварийного дампа. Если не хватает, то или использую пошаговый дамп поля зрения (смотрю несколько шагов, предшествующих падению) или вставляю `WriteLine`. Соответственно, из символьной информации во время выполнения доступны только имена функций.

Отладка на уровне исходного кода [сейчас исследуется](./49) в рамках курсового проекта (к сожалению, он ещё не готов — будет готов минимум в январе, максимум в апреле) — предполагается символьную информацию (имена переменных) внедрять в интерпретируемый код, а интерпретатор научить это понимать.

Отлаживать отладчиком C++ код на Рефале бессмысленно — разумно им пользоваться только при отладке внешних функций на C++ и рантайма. Об этом, кстати, написано в шестом разделе [руководства](../blob/master/doc/manul.pdf).

**Comment by Mazdaywik** [comment]
Для полноты картины должен быть также реализован интерпретатор — аналог `refgo`.

**Comment by Mazdaywik** [comment]
Как создать интерпретатор — аналог `refgo`? Есть два основных варианта:

* Написать его на Рефале — он будет читать из командной строки имя модуля, загружать его динамически при помощи `Module-Load`, вызывать оттуда `Go` или `GO`, а потом выгружать.
* Написать его на C++.

Хотелось бы иметь возможность задавать диагностические флаги командной строки — указывать в командной строке те опции, которые по умолчанию читаются из `@refal-5-lambda-diagnostics.ini`.

Если писать интерпретатор на C++, то разобрать командную строку и задать отладочные флаги сравнительно несложно. Но писать код интерпретатора будет громоздко. Или придётся продублировать `exe/refalrts-main.cpp`, где помимо запуска программы инициализируется таблица колбэков `refalrts::VMapi`, или последний как-то надо будет рефакторизовывать.

Если писать интерпретатор на Рефале, то задавать диагностические опции так просто не получится. Или придётся ограничиться ключом `++diagnostic+config=filename.ini`, или использовать нативную вставку для разбора ключей.

**Comment by Mazdaywik** [comment]
Предлагается писать интерпретатор на Рефале с нативной вставкой для разбора аргументов командной строки.

Кроме того, интерпретатор всегда будет собираться в отладочном режиме (`--debug`). Для релизного режима есть компиляция в исполнимый файл.

Имя файла интерпретатора будет `srefgo`.

**Comment by Mazdaywik** [comment]
Не, `srefgo` не очень подходящее имя, поскольку Простой Рефал deprecated.
